version: '2'
services:
  cas-server:
    container_name: cas-server
    build: cas-server/
    mem_limit: 1g
    ports:
     - "8080:8080"
    volumes:
      - ./services:/services
      - ./logs:/logs
    depends_on:
      - memcached
      - elasticsearch
      - filebeat
  filebeat:
    container_name: filebeat
    build: filebeat/
    mem_limit: 256m
    volumes:
      - ./logs:/logs
  memcached:
    container_name: memcached
    image: memcached:1.4.36-alpine
    mem_limit: 256m
    ports:
     - "11211:11211"
    command: memcached -m 192m
  logstash:
    container_name: logstash
    build: logstash/
    mem_limit: 1g
    ports:
     - "5044:5044"
     - "9600:9600"
    depends_on:
     - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - cluster.name=escascluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    ports:
     - "9200:9200"
     - "9300:9300"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.3.0
    mem_limit: 1g
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch