version: '2'
services:
  cas-server:
    container_name: cas-server
    build: cas-server/
    mem_limit: 640m
    ports:
     - "8080:8080"
    volumes:
      - ./cas-server/services:/services
    depends_on:
      - memcached
      - elasticsearch
  cas-management:
    container_name: cas-management
    build: cas-management/
    mem_limit: 384m
    ports:
     - "8081:8081"
    depends_on:
      - memcached
      - cas-server
    volumes:
      - ./cas-server/services:/services
  memcached:
    container_name: memcached
    image: memcached:1.4.36-alpine
    mem_limit: 256m
    ports:
     - "11211:11211"
    command: memcached -m 256m
  logstash:
    container_name: logstash
    build: logstash/
    mem_limit: 768m
    ports:
     - "5044:5044"
     - "9600:9600"
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - cluster.name=escascluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
     - "9200:9200"
     - "9300:9300"
    depends_on:
     - logstash