version: '3'
services:
  cas-server:
    container_name: cas-server
    build: cas-server/
    ports:
     - "8080:8080"
    depends_on:
      - couchbase
      - elasticsearch
  couchbase:
    container_name: couchbase
    image: couchbase/server:4.6.1
    ports:
     - "8091-8094:8091-8094"
     - "11210:11210"
    ulimits:
      nofile: 40960
      core: 100000000
      memlock: 100000000
    volumes:
      - ./couchbase/var:/opt/couchbase/var
  logstash:
    container_name: logstash
    build: logstash/
    ports:
     - "5044:5044"
     - "9600:9600"
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
     - "9200:9200"
     - "9300:9300"
    depends_on:
     - logstash