version: '3'
services:
  cas-server:
    container_name: cas-server
    build: cas-server/
    ports:
     - "8080:8080"
    volumes:
     - ./cas-server/target:/target
    links:
      - couchbase
    depends_on:
      - couchbase
  couchbase:
    container_name: couchbase
    image: couchbase/server:4.6.1
    ports:
     - "8091-8094:8091-8094"
     - "11210:11210"
    ulimits:
      nproc: 65535
      nofile:
        soft: 40960
        hard: 40960
    volumes:
      - ./couchbase/var:/opt/couchbase/var
