version: '3'
services:
  couchbase:
    container_name: couchbase
    image: couchbase/server:4.6.1
    ports:
     - "8091-8094:8091-8094"
     - "11210:11210"
    ulimits:
      nofile: 40960
      core: 100000000
      memlock: 100000000
    volumes:
      - ./var:/opt/couchbase/var